### ISSUE TITLE
KanBan Board

### ISSUE THREAD

**Issue by see-why** [see-why/Rockets-React-Redux#26]
[Project KanBan board](https://github.com/see-why/Rockets-React-Redux/projects/1)

It is a team of 2 people.

**Comment by Davidosky007** [comment]
## Hi @see-why @BenMukebo 👋, 

## Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

![well-done](https://user-images.githubusercontent.com/52497246/140724486-53675f46-a0e6-4a29-ba50-64880bf3e5bc.jpg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by see-why** [comment]
@Davidosky007 

Thanks a lot.
Have a great day.
